# Generated by Django 4.2.2 on 2023-06-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('0', 'iphone'), ('1', 'samsung'), ('2', 'xiaomi'), ('3', 'redmi')], max_length=100)),
                ('type', models.CharField(choices=[('0', 'all'), ('1', 'hot'), ('2', 'sale'), ('3', 'new')], max_length=10)),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
